name: cyclone
description: Weight tracker that accounts for menstruation.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  go_router: ^6.5.2
  emojis: ^0.9.9
  provider: ^6.0.5
  sqflite: ^2.2.6
  path: ^1.8.2
  get_it: ^7.2.0
  charts_painter: ^3.1.1
  intl: ^0.18.0
  flutter_launcher_icons: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - mock_data/
    - assets/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
